services:
  radio-runner:
    build: .
    image: radio-runner:local
    restart: unless-stopped
    env_file:
      - .env
    group_add:
      - "998"
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=radio"
      - "docktail.service.port=8000"
      - "docktail.service.service-protocol=https"
      - "docktail.service.1.name=radio"
      - "docktail.service.1.port=8000"
      - "docktail.service.1.service-protocol=http"
